CREATE USER developer WITH PASSWORD 'developer';
GRANT USAGE ON SCHEMA FinanSys TO developer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FinanSys TO developer;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FinanSys TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA FinanSys GRANT ALL ON TABLES TO developer;

CREATE USER usuario WITH PASSWORD 'usuario';
GRANT USAGE ON SCHEMA FinanSys TO usuario;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FinanSys TO usuario;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FinanSys TO usuario;
ALTER DEFAULT PRIVILEGES IN SCHEMA FinanSys GRANT ALL ON TABLES TO usuario;