# backend/Dockerfile
FROM python:3.9-slim

# Instalación de dependencias necesarias
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Instalar Airflow y las dependencias del proyecto
ENV AIRFLOW_HOME=/airflow
RUN pip install --no-cache-dir apache-airflow==2.7.2

# Instalar dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del proyecto
COPY ./app /app
WORKDIR /app

# Comando para iniciar Airflow
CMD ["airflow", "webserver"]
